name: Build and Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-ffmpeg:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      cache-hit: ${{ steps.cache-ffmpeg.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache FFmpeg
        id: cache-ffmpeg
        uses: actions/cache@v3
        with:
          path: src/exec
          key: ffmpeg-${{ matrix.os }}-v1
          restore-keys: |
            ffmpeg-${{ matrix.os }}-
      
      - name: Download FFmpeg for Windows
        if: matrix.os == 'windows-latest' && steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: |
          $url = "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip"
          Invoke-WebRequest -Uri $url -OutFile ffmpeg.zip
          Expand-Archive ffmpeg.zip -DestinationPath ffmpeg_temp
          New-Item -ItemType Directory -Force -Path src/exec
          Get-ChildItem -Path ffmpeg_temp -Recurse -Filter "ffmpeg.exe" | 
            Select-Object -First 1 | 
            ForEach-Object { Copy-Item $_.FullName -Destination "src/exec/ffmpeg.exe" }
        shell: pwsh

      - name: Download FFmpeg for macOS
        if: matrix.os == 'macos-latest' && steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: |
          curl -L https://evermeet.cx/ffmpeg/ffmpeg-6.1.zip -o ffmpeg.zip
          unzip ffmpeg.zip
          mkdir -p src/exec
          mv ffmpeg src/exec/
          chmod +x src/exec/ffmpeg

      - name: Sign FFmpeg (macOS)
        if: matrix.os == 'macos-latest' && steps.cache-ffmpeg.outputs.cache-hit != 'true'
        env:
          CERTIFICATE_BASE64: ${{ secrets.SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain
          /usr/bin/codesign --force -s "Developer ID Application: mickael ducatez (9H8DB46V75)" --options runtime src/exec/ffmpeg

      - name: Upload FFmpeg artifact
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-${{ matrix.os }}
          path: src/exec/

  build-executables:
    needs: build-ffmpeg
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache executable
        id: cache-executable
        uses: actions/cache@v3
        with:
          path: |
            build/YoutubetoPremiere
            src/exec
          key: executable-${{ matrix.os }}-${{ hashFiles('app/**', 'requirements.txt', 'YoutubetoPremiere.spec') }}-v1
          restore-keys: |
            executable-${{ matrix.os }}-
      
      - name: Setup Python
        if: steps.cache-executable.outputs.cache-hit != 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Cache Python dependencies
        if: steps.cache-executable.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          
      - name: Install Python dependencies
        if: steps.cache-executable.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pygame
          
      - name: Download FFmpeg artifact
        if: steps.cache-executable.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v3
        with:
          name: ffmpeg-${{ matrix.os }}
          path: src/exec/
          
      - name: Make FFmpeg executable (macOS)
        if: matrix.os == 'macos-latest' && steps.cache-executable.outputs.cache-hit != 'true'
        run: chmod +x src/exec/ffmpeg
        
      - name: Build executable
        if: steps.cache-executable.outputs.cache-hit != 'true'
        run: python -m PyInstaller YoutubetoPremiere.spec -y --workpath build/work --distpath build/YoutubetoPremiere
        shell: bash

      - name: Sign executable (macOS)
        if: matrix.os == 'macos-latest' && steps.cache-executable.outputs.cache-hit != 'true'
        env:
          CERTIFICATE_BASE64: ${{ secrets.SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain
          /usr/bin/codesign --force -s "Developer ID Application: mickael ducatez (9H8DB46V75)" --options runtime build/YoutubetoPremiere/YoutubetoPremiere
          find build/YoutubetoPremiere -name "*.dylib" -exec /usr/bin/codesign --force -s "Developer ID Application: mickael ducatez (9H8DB46V75)" --options runtime {} \;

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable-${{ matrix.os }}
          path: |
            build/YoutubetoPremiere/**/*
            src/exec/ffmpeg*

  package-zxp:
    needs: build-executables
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Create directories
        shell: pwsh
        run: New-Item -ItemType Directory -Force -Path dist/cep/exec
          
      - name: Download Windows artifacts
        uses: actions/download-artifact@v3
        with:
          name: executable-windows-latest
          path: dist/cep/exec/windows-latest

      - name: Download macOS artifacts
        uses: actions/download-artifact@v3
        with:
          name: executable-macos-latest
          path: dist/cep/exec/macos-latest

      - name: Organize files
        shell: pwsh
        run: |
          # Organize files
          Copy-Item -Path "dist/cep/exec/windows-latest/build/YoutubetoPremiere/YoutubetoPremiere.exe" -Destination "dist/cep/exec/" -ErrorAction SilentlyContinue
          if (-not $?) { Write-Host "Windows exe not found" }
          
          Copy-Item -Path "dist/cep/exec/windows-latest/src/exec/ffmpeg.exe" -Destination "dist/cep/exec/" -ErrorAction SilentlyContinue
          if (-not $?) { Write-Host "Windows FFmpeg not found" }
          
          Copy-Item -Path "dist/cep/exec/macos-latest/build/YoutubetoPremiere/YoutubetoPremiere" -Destination "dist/cep/exec/" -ErrorAction SilentlyContinue
          if (-not $?) { Write-Host "macOS executable not found" }
          
          Copy-Item -Path "dist/cep/exec/macos-latest/src/exec/ffmpeg" -Destination "dist/cep/exec/" -ErrorAction SilentlyContinue
          if (-not $?) { Write-Host "macOS FFmpeg not found" }
          
          # Remove temporary directories
          Remove-Item -Path "dist/cep/exec/windows-latest" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "dist/cep/exec/macos-latest" -Recurse -Force -ErrorAction SilentlyContinue

      - name: Build ZXP
        env:
          ZXP_PACKAGE: true
          SKIP_PYTHON_BUILD: true
        run: yarn zxp

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/zxp/*.zxp
          generate_release_notes: true
