name: Build and Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      package_only:
        description: 'Only run the packaging step (uses latest successful build artifacts)'
        type: boolean
        default: false
      version:
        description: 'Version to use for the release (e.g. 3.0.5)'
        required: false
        default: ''

permissions:
  contents: write
  actions: read

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      app_changed: ${{ steps.filter.outputs.app_changed }}
      tag_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check if package_only is enabled
        id: check_package_only
        run: |
          if [[ "${{ github.event.inputs.package_only }}" == "true" ]]; then
            echo "package_only=true" >> $GITHUB_OUTPUT
            if [[ -n "${{ github.event.inputs.version }}" ]]; then
              echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            else
              # Default to the latest tag if no version is specified
              latest_tag=$(git describe --tags --abbrev=0)
              echo "version=${latest_tag#v}" >> $GITHUB_OUTPUT
            fi
          else
            echo "package_only=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Check for app changes
        id: filter
        run: |
          if [[ "${{ steps.check_package_only.outputs.package_only }}" == "true" ]]; then
            echo "Skipping change detection as package_only is enabled"
            echo "app_changed=true" >> $GITHUB_OUTPUT
          else
            # Normal change detection
            if [[ "${{ github.event_name }}" == "push" && "${{ startsWith(github.ref, 'refs/tags/v') }}" == "true" ]]; then
              echo "app_changed=true" >> $GITHUB_OUTPUT
            else
              echo "No app changes detected or not a tagged push event"
              echo "app_changed=false" >> $GITHUB_OUTPUT
            fi
          fi
        shell: bash

      - name: Extract version from tag or input
        id: get_version
        run: |
          if [[ "${{ steps.check_package_only.outputs.package_only }}" == "true" ]]; then
            echo "version=${{ steps.check_package_only.outputs.version }}" >> $GITHUB_OUTPUT
          else
            if [[ "${{ github.event_name }}" == "push" && "${{ startsWith(github.ref, 'refs/tags/v') }}" == "true" ]]; then
              version=${GITHUB_REF#refs/tags/v}
              echo "version=$version" >> $GITHUB_OUTPUT
            else
              echo "version=0.0.0" >> $GITHUB_OUTPUT
            fi
          fi
        shell: bash

  build-ffmpeg:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.app_changed == 'true' && github.event.inputs.package_only != 'true' }}
    strategy:
      matrix:
        os: [windows-latest, macos-13]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    outputs:
      windows_ffmpeg_path: ${{ steps.output_paths.outputs.win_ffmpeg_path }}
      macos_ffmpeg_path: ${{ steps.output_paths.outputs.mac_ffmpeg_path }}
    steps:
      - name: Check FFmpeg cache
        id: ffmpeg-cache
        uses: actions/cache@v4
        with:
          path: |
            ffmpeg${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          key: ffmpeg-${{ matrix.os }}-v2
      
      - name: Output FFmpeg paths
        id: output_paths
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            echo "win_ffmpeg_path=ffmpeg.exe" >> $GITHUB_OUTPUT
          else
            echo "mac_ffmpeg_path=ffmpeg" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Download and process FFmpeg
        if: steps.ffmpeg-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        
      - name: Download FFmpeg for Windows
        if: matrix.os == 'windows-latest' && steps.ffmpeg-cache.outputs.cache-hit != 'true'
        run: |
          $url = "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip"
          Invoke-WebRequest -Uri $url -OutFile ffmpeg.zip
          Expand-Archive ffmpeg.zip -DestinationPath ffmpeg_temp
          Get-ChildItem -Path ffmpeg_temp -Recurse -Filter "ffmpeg.exe" | 
            Select-Object -First 1 | 
            ForEach-Object { Copy-Item $_.FullName -Destination "ffmpeg.exe" }
          Remove-Item -Path ffmpeg.zip -Force
          Remove-Item -Path ffmpeg_temp -Recurse -Force
        shell: pwsh

      - name: Download FFmpeg for macOS
        if: matrix.os == 'macos-13' && steps.ffmpeg-cache.outputs.cache-hit != 'true'
        run: |
          curl -L https://evermeet.cx/ffmpeg/ffmpeg-6.1.zip -o ffmpeg.zip
          unzip ffmpeg.zip
          chmod +x ffmpeg
          rm -f ffmpeg.zip

      - name: Sign FFmpeg (macOS)
        if: matrix.os == 'macos-13' && steps.ffmpeg-cache.outputs.cache-hit != 'true'
        env:
          CERTIFICATE_BASE64: ${{ secrets.SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain
          /usr/bin/codesign --force -s "Developer ID Application: mickael ducatez (9H8DB46V75)" --options runtime ffmpeg
          rm -f certificate.p12

      - name: Upload FFmpeg artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-${{ matrix.os }}
          path: ffmpeg${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          retention-days: 7

  build-executables:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.app_changed == 'true' && github.event.inputs.package_only != 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-13]
      fail-fast: false
    outputs:
      win_exe_path: ${{ steps.output_paths.outputs.win_exe_path }}
      mac_exe_path: ${{ steps.output_paths.outputs.mac_exe_path }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Output executable paths
        id: output_paths
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            echo "win_exe_path=YoutubetoPremiere.exe" >> $GITHUB_OUTPUT
          else
            echo "mac_exe_path=YoutubetoPremiere" >> $GITHUB_OUTPUT
          fi
        shell: bash
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller pygame
        
      - name: Build executable
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            python -m PyInstaller YoutubetoPremiere.spec -y --workpath build/work --distpath ./
          else
            python -m PyInstaller YoutubetoPremiere.local.spec -y --workpath build/work --distpath ./
          fi
      
      - name: Sign executable (macOS)
        if: matrix.os == 'macos-13'
        env:
          CERTIFICATE_BASE64: ${{ secrets.SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain
          /usr/bin/codesign --force -s "Developer ID Application: mickael ducatez (9H8DB46V75)" --options runtime YoutubetoPremiere
          find . -name "*.dylib" -exec /usr/bin/codesign --force -s "Developer ID Application: mickael ducatez (9H8DB46V75)" --options runtime {} \;
          rm -f certificate.p12

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: executable-${{ matrix.os }}
          path: |
            ${{ matrix.os == 'windows-latest' && 'YoutubetoPremiere.exe' || 'YoutubetoPremiere' }}
          retention-days: 7
          if-no-files-found: error

  package-zxp:
    needs: [check-changes, build-ffmpeg, build-executables]
    if: ${{ needs.check-changes.outputs.app_changed == 'true' }}
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn global add cross-env
        
      - name: Add global yarn bin to PATH
        run: echo "$(yarn global bin)" >> $GITHUB_PATH
        shell: bash
      
      - name: Create directories
        run: |
          mkdir -p dist/cep/exec/sounds
          mkdir -p backup/exec
        shell: bash

      - name: Download artifacts from current workflow
        if: ${{ github.event.inputs.package_only != 'true' }}
        uses: actions/download-artifact@v4
        
      - name: Download artifacts from previous workflow
        if: ${{ github.event.inputs.package_only == 'true' }}
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          workflow_conclusion: success
          name_is_regexp: true
          name: .*
          path: artifacts
      
      - name: List downloaded artifacts
        run: |
          if [[ "${{ github.event.inputs.package_only }}" == "true" ]]; then
            find artifacts -type f | sort
          else
            ls -la
          fi
        shell: bash

      - name: Optimize ZXP packaging process
        shell: bash
        env:
          SKIP_PYTHON_BUILD: true
          NO_PYTHON: true
          ZXP_PACKAGE: true
        run: |
          # Function to copy artifacts with error checking
          copy_artifact() {
            local source=$1
            local dest=$2
            local description=$3
            
            if [ -f "$source" ]; then
              cp "$source" "$dest"
              echo "✓ Copied $description"
            else
              echo "✗ ERROR: $description not found at: $source"
              return 1
            fi
          }
          
          echo "===== PREPARING ZXP PACKAGE ====="
          
          # Create backup of executables
          mkdir -p backup/exec
          
          # Copy all Python files
          echo "Copying Python files..."
          cp app/*.py dist/cep/exec/ 2>/dev/null || echo "No Python files found"
          cp -r app/sounds/* dist/cep/exec/sounds/ 2>/dev/null || echo "No sound files found"
          
          # Copy artifacts efficiently
          echo "Copying executables and FFmpeg..."
          
          # Windows executable
          copy_artifact "artifacts/executable-windows-latest/YoutubetoPremiere.exe" "dist/cep/exec/" "Windows executable"
          copy_artifact "artifacts/executable-windows-latest/YoutubetoPremiere.exe" "backup/exec/" "Windows executable (backup)"
          
          # Windows FFmpeg
          copy_artifact "artifacts/ffmpeg-windows-latest/ffmpeg.exe" "dist/cep/exec/" "Windows FFmpeg"
          copy_artifact "artifacts/ffmpeg-windows-latest/ffmpeg.exe" "backup/exec/" "Windows FFmpeg (backup)"
          
          # macOS executable
          copy_artifact "artifacts/executable-macos-13/YoutubetoPremiere" "dist/cep/exec/" "macOS executable"
          copy_artifact "artifacts/executable-macos-13/YoutubetoPremiere" "backup/exec/" "macOS executable (backup)"
          
          # macOS FFmpeg
          copy_artifact "artifacts/ffmpeg-macos-13/ffmpeg" "dist/cep/exec/" "macOS FFmpeg"
          copy_artifact "artifacts/ffmpeg-macos-13/ffmpeg" "backup/exec/" "macOS FFmpeg (backup)"
          
          # Verify files are in place
          echo "Verifying files in dist/cep/exec before yarn zxp:"
          ls -la dist/cep/exec
          
          # Build TypeScript
          echo "Building TypeScript..."
          yarn tsc -p "tsconfig-build.json"
          
          # We'll use a simpler approach - use yarn zxp to create the package, then modify it
          echo "Running initial yarn zxp..."
          yarn zxp
          
          # Verify the ZXP exists
          if [ ! -f "dist/zxp/com.youtubetoPremiereV2.cep.zxp" ]; then
            echo "ERROR: yarn zxp did not create the ZXP package"
            exit 1
          fi
          
          echo "Extracting the ZXP package..."
          mkdir -p zxp_extract
          cp dist/zxp/com.youtubetoPremiereV2.cep.zxp zxp_extract/
          cd zxp_extract
          unzip -q com.youtubetoPremiereV2.cep.zxp -d contents || echo "Could not extract ZXP"
          cd ..
          
          echo "Creating exec directory in the extracted package..."
          mkdir -p zxp_extract/contents/exec
          
          echo "Copying executables to the extracted package..."
          cp backup/exec/* zxp_extract/contents/exec/ 2>/dev/null || echo "No executables found in backup"
          cp app/*.py zxp_extract/contents/exec/ 2>/dev/null || echo "No Python files found"
          mkdir -p zxp_extract/contents/exec/sounds
          cp -r app/sounds/* zxp_extract/contents/exec/sounds/ 2>/dev/null || echo "No sound files found"
          
          echo "Verifying executables are in the extracted package:"
          ls -la zxp_extract/contents/exec
          
          echo "===== ZXP PACKAGING COMPLETED ====="

      - name: Create Final ZXP with Executables
        shell: pwsh
        run: |
          Write-Host "===== CREATING FINAL ZXP WITH EXECUTABLES ====="
          
          # Ensure the directories exist
          if (-Not (Test-Path "zxp_extract/contents")) {
            Write-Error "Contents directory not found! Packaging failed."
            exit 1
          }
          
          # Verify executables exist
          $exePath = "zxp_extract/contents/exec/YoutubetoPremiere.exe"
          $ffmpegPath = "zxp_extract/contents/exec/ffmpeg.exe"
          
          if (Test-Path $exePath) {
            Write-Host "✓ Found Windows executable: $exePath"
          } else {
            Write-Host "✗ WARNING: Windows executable not found!"
          }
          
          if (Test-Path $ffmpegPath) {
            Write-Host "✓ Found Windows FFmpeg: $ffmpegPath"
          } else {
            Write-Host "✗ WARNING: Windows FFmpeg not found!"
          }
          
          # Create the new ZXP file
          Write-Host "Creating ZXP file..."
          Add-Type -Assembly System.IO.Compression.FileSystem
          $compressionLevel = [System.IO.Compression.CompressionLevel]::Optimal
          
          # Make sure the destination directory exists
          if (-Not (Test-Path "dist/zxp")) {
            New-Item -Path "dist/zxp" -ItemType Directory
          }
          
          # Remove existing ZXP if it exists
          if (Test-Path "dist/zxp/com.youtubetoPremiereV2.cep.zxp") {
            Remove-Item "dist/zxp/com.youtubetoPremiereV2.cep.zxp" -Force
          }
          
          # Create new ZXP
          [System.IO.Compression.ZipFile]::CreateFromDirectory("zxp_extract/contents", "dist/zxp/com.youtubetoPremiereV2.cep.zxp", $compressionLevel, $false)
          
          # Verify the ZXP was created
          if (Test-Path "dist/zxp/com.youtubetoPremiereV2.cep.zxp") {
            $fileSize = (Get-Item "dist/zxp/com.youtubetoPremiereV2.cep.zxp").Length / 1MB
            Write-Host "✓ ZXP package created successfully: $fileSize MB"
            
            # Examine contents
            Write-Host "Examining ZXP contents..."
            try {
              $zip = [System.IO.Compression.ZipFile]::OpenRead("dist/zxp/com.youtubetoPremiereV2.cep.zxp")
              
              # Look for executables
              $exeFiles = $zip.Entries | Where-Object { $_.Name -like "*.exe" }
              if ($exeFiles.Count -gt 0) {
                Write-Host "✓ Found .exe files in ZXP:"
                $exeFiles | ForEach-Object { Write-Host "  - $_" }
              } else {
                Write-Host "✗ WARNING: No .exe files found in ZXP!"
              }
              
              # Look for FFmpeg
              $ffmpegFiles = $zip.Entries | Where-Object { $_.Name -like "*ffmpeg*" }
              if ($ffmpegFiles.Count -gt 0) {
                Write-Host "✓ Found ffmpeg files in ZXP:"
                $ffmpegFiles | ForEach-Object { Write-Host "  - $_" }
              } else {
                Write-Host "✗ WARNING: No ffmpeg files found in ZXP!"
              }
              
              $zip.Dispose()
            } catch {
              Write-Host "Error examining ZXP content: $_"
            }
          } else {
            Write-Error "Failed to create ZXP package!"
            exit 1
          }
          
          Write-Host "===== FINAL ZXP PACKAGING COMPLETED ====="

      - name: Verify and Rename ZXP Package
        shell: pwsh
        run: |
          $version = "${{ needs.check-changes.outputs.tag_version }}"
          
          if (Test-Path "dist/zxp/com.youtubetoPremiereV2.cep.zxp") {
            # Rename the ZXP file to include the version
            $newName = "YoutubetoPremiere-v$version.zxp"
            Copy-Item -Path "dist/zxp/com.youtubetoPremiereV2.cep.zxp" -Destination "dist/zxp/$newName" -Force
            Write-Host "Renamed ZXP package to: $newName"
            
            # Remove the original file
            Remove-Item -Path "dist/zxp/com.youtubetoPremiereV2.cep.zxp" -Force
            
            # List the files
            Get-ChildItem -Path dist/zxp
          } else {
            Write-Error "ZXP package was not found!"
            exit 1
          }

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/zxp/YoutubetoPremiere-v${{ needs.check-changes.outputs.tag_version }}.zxp
          name: YoutubetoPremiere v${{ needs.check-changes.outputs.tag_version }}
          tag_name: v${{ needs.check-changes.outputs.tag_version }}
          generate_release_notes: true
