name: Build and Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pygame
          
      - name: Setup Keychain
        env:
          CERTIFICATE_BASE64: ${{ secrets.SIGNING_CERTIFICATE }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # Create keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -l build.keychain
          
          # Import certificate
          echo "$CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$KEYCHAIN_PASSWORD" -T /usr/bin/codesign
          
          # Update keychain settings
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          
      - name: Build executable
        run: python -m PyInstaller YoutubetoPremiere.spec -y --workpath build/work --distpath build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-macos-latest
          path: build/
          
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pygame
          
      - name: Build executable
        run: python -m PyInstaller YoutubetoPremiere.spec -y --workpath build/work --distpath build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-windows-latest
          path: build/

  package:
    needs: [build-mac, build-windows]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          yarn install
          python -m pip install -r requirements.txt
          python -m pip install pygame

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Move executables
        shell: pwsh
        run: |
          # Create exec directory if it doesn't exist
          New-Item -ItemType Directory -Force -Path dist/cep/exec
          
          # Move Windows executable
          $winExe = Get-ChildItem -Path artifacts/dist-windows-latest -Recurse -Filter "YoutubetoPremiere.exe" | Select-Object -First 1
          if ($winExe) {
            Copy-Item -Force $winExe.FullName "dist/cep/exec/"
            Write-Host "Copied Windows executable: $($winExe.FullName)"
          } else {
            Write-Host "Windows executable not found!"
          }
          
          # Move macOS executable
          $macExe = Get-ChildItem -Path artifacts/dist-macos-latest -Recurse -Filter "YoutubetoPremiere" | Select-Object -First 1
          if ($macExe) {
            Copy-Item -Force $macExe.FullName "dist/cep/exec/"
            Write-Host "Copied macOS executable: $($macExe.FullName)"
          } else {
            Write-Host "macOS executable not found in: $(Get-ChildItem -Path artifacts/dist-macos-latest -Recurse | ForEach-Object { $_.FullName })"
          }

      - name: Build and Package CEP Extension
        shell: pwsh
        run: |
          # First build the CEP extension
          yarn build
          
          # Create exec directory if it doesn't exist
          New-Item -ItemType Directory -Force -Path "dist/cep/exec" | Out-Null
          
          # Copy executables to the exec folder
          Write-Host "Copying executables..."
          Copy-Item "artifacts/dist-windows-latest/YoutubetoPremiere.exe" -Destination "dist/cep/exec/" -Force
          Copy-Item "artifacts/dist-macos-latest/YoutubetoPremiere" -Destination "dist/cep/exec/" -Force
          
          # Create sounds directory and copy sounds
          Write-Host "Copying sounds..."
          New-Item -ItemType Directory -Force -Path "dist/cep/exec/sounds" | Out-Null
          Copy-Item "app/sounds/*" -Destination "dist/cep/exec/sounds/" -Force -Recurse
          
          # Verify files before packaging
          Write-Host "Contents of dist/cep/exec directory before packaging:"
          Get-ChildItem -Recurse "dist/cep/exec" | ForEach-Object { Write-Host $_.FullName }
          
          # Create the extension package
          Write-Host "Creating ZXP package..."
          yarn zxp
          
          # Verify the contents of the ZXP
          Write-Host "Contents of dist/zxp directory:"
          Get-ChildItem -Recurse "dist/zxp" | ForEach-Object { Write-Host $_.FullName }
          
          # Verify the final dist directory structure
          Write-Host "Final contents of dist directory:"
          Get-ChildItem -Recurse dist | ForEach-Object { Write-Host $_.FullName }

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ./dist/zxp/*.zxp
          generate_release_notes: true
