name: Build and Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  actions: read
  checks: read
  issues: read
  packages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  build-ffmpeg:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Download FFmpeg for Windows
        if: matrix.os == 'windows-latest'
        run: |
          $url = "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip"
          Invoke-WebRequest -Uri $url -OutFile ffmpeg.zip
          Expand-Archive ffmpeg.zip -DestinationPath ffmpeg_temp
          Get-ChildItem -Path ffmpeg_temp -Recurse -Filter "ffmpeg.exe" | 
            Select-Object -First 1 | 
            ForEach-Object { Copy-Item $_.FullName -Destination "ffmpeg.exe" }
          Remove-Item -Path ffmpeg.zip -Force
          Remove-Item -Path ffmpeg_temp -Recurse -Force
        shell: pwsh

      - name: Download FFmpeg for macOS
        if: matrix.os == 'macos-latest'
        run: |
          curl -L https://evermeet.cx/ffmpeg/ffmpeg-6.1.zip -o ffmpeg.zip
          unzip ffmpeg.zip
          chmod +x ffmpeg
          rm -f ffmpeg.zip

      - name: Sign FFmpeg (macOS)
        if: matrix.os == 'macos-latest'
        env:
          CERTIFICATE_BASE64: ${{ secrets.SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain
          /usr/bin/codesign --force -s "Developer ID Application: mickael ducatez (9H8DB46V75)" --options runtime ffmpeg

      - name: Upload FFmpeg artifact
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-${{ matrix.os }}
          path: ffmpeg*

  build-executables:
    needs: build-ffmpeg
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pygame
          
      - name: Download FFmpeg artifact
        uses: actions/download-artifact@v3
        with:
          name: ffmpeg-${{ matrix.os }}
          path: ./
      
      - name: Make FFmpeg executable (macOS)
        if: matrix.os == 'macos-latest'
        run: chmod +x ffmpeg
        
      - name: Build executable
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            python -m PyInstaller YoutubetoPremiere.spec -y --workpath build/work --distpath ./
          else
            python -m PyInstaller YoutubetoPremiere.local.spec -y --workpath build/work --distpath ./
          fi
      
      - name: Sign executable (macOS)
        if: matrix.os == 'macos-latest'
        env:
          CERTIFICATE_BASE64: ${{ secrets.SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain
          /usr/bin/codesign --force -s "Developer ID Application: mickael ducatez (9H8DB46V75)" --options runtime YoutubetoPremiere
          find . -name "*.dylib" -exec /usr/bin/codesign --force -s "Developer ID Application: mickael ducatez (9H8DB46V75)" --options runtime {} \;

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable-${{ matrix.os }}
          path: |
            YoutubetoPremiere*
            ffmpeg*

  package-zxp:
    needs: build-executables
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Create exec directory
        run: mkdir -p dist/cep/exec
        shell: bash

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Copy executables and FFmpeg to CEP directory
        shell: pwsh
        run: |
          # Create exec directory if it doesn't exist
          New-Item -ItemType Directory -Force -Path dist/cep/exec
          
          # Debug: List artifacts directory contents
          Write-Host "Contents of artifacts directory:"
          Get-ChildItem -Path artifacts -Recurse
          
          # Copy Windows artifacts
          if (Test-Path "artifacts/executable-windows-latest") {
              Write-Host "Copying Windows artifacts..."
              Copy-Item -Path "artifacts/executable-windows-latest/*" -Destination "dist/cep/exec/" -Force
          } else {
              Write-Error "Windows artifacts directory not found!"
          }
          
          # Copy macOS artifacts
          if (Test-Path "artifacts/executable-macos-latest") {
              Write-Host "Copying macOS artifacts..."
              Copy-Item -Path "artifacts/executable-macos-latest/*" -Destination "dist/cep/exec/" -Force
          } else {
              Write-Error "macOS artifacts directory not found!"
          }
          
          # List contents to verify
          Write-Host "Contents of dist/cep/exec:"
          Get-ChildItem -Path dist/cep/exec

      - name: Build CEP Extension
        env:
          SKIP_PYTHON_BUILD: true
          NO_PYTHON: true
        run: |
          yarn clean
          yarn tsc -p "tsconfig-build.json"
          yarn cross-env vite build --force --watch false

      - name: Package ZXP
        env:
          SKIP_PYTHON_BUILD: true
          NO_PYTHON: true
          ZXP_PACKAGE: true
        run: yarn zxp

      - name: Verify ZXP Package
        shell: pwsh
        run: |
          if (-not (Test-Path "dist/zxp/*.zxp")) {
              Write-Error "ZXP package was not created!"
              exit 1
          }
          Write-Host "ZXP package created successfully"
          Get-ChildItem -Path dist/zxp

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/zxp/*.zxp
          generate_release_notes: true
